nodeLinker: pnp

npmScopes:
  codestates-engineering:
    npmAlwaysAuth: true
    npmAuthToken: '${CSE_NPM_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.3.1.cjs
