nodeLinker: pnp

npmScopes:
  codestates-engineering:
    npmAlwaysAuth: true
    npmAuthToken: "${CSE_NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
