name: CD

on:
  push:
    branches:
      - 'release'

env:
  NODE_VERSION: "18.13"
  NPM_REGISTRY_URL: 'https://npm.pkg.github.com/'

jobs:
  package:
    if: "!contains(github.event.head_commit.message, 'ver: ')"
    runs-on: ubuntu-latest
    env:
      CSE_NPM_TOKEN: ${{secrets.CSE_NPM_TOKEN}}

    steps:
      - name: node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}

      - name: depenency(zero-install) install
        run: yarn install

      - name: author registration
        run: git config --global user.email "engineering@codestates.com" && git config --global user.name "CodeStates Engineering"

      - name: git pull
        run: git pull

      - name: patch versioning
        if: "!contains(github.event.head_commit.message, 'version-up ')"
        run: "npm version patch -m 'ver: %s'"

      - name: minor versioning
        if: "contains(github.event.head_commit.message, 'version-up minor')"
        run: "npm version minor -m 'ver: %s'"

      - name: major versioning
        if: "contains(github.event.head_commit.message, 'version-up major')"
        run: "npm version major -m 'ver: %s'"

      - name: git push
        run: git push

      - name: package(canary) deployment
        run: yarn run deploy:package

      - name: tag version extraction
        run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        id: extract_version_name

      - name: release creation
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version_name.outputs.version }}
          release_name: ${{ steps.extract_version_name.outputs.version }}