name: Check code style

on:
  pull_request:
    branches: ['release']

jobs:
  check_code_style:
    runs-on: ubuntu-latest
    env:
      CSE_NPM_TOKEN: ${{secrets.CSE_NPM_TOKEN}}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}

      - name: Set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}
      
      - name: Install depenency
        run: pnpm install

      - name: Check eslint
        run: pnpm lint

      - name: Check prettier
        run: pnpm prettier

      - name: Check stylelint
        run: pnpm lint:style
