name: PR Test

on:
  pull_request:
    branches: ['release']

jobs:
  check_build:
    runs-on: ubuntu-latest
    env:
      CSE_NPM_TOKEN: ${{secrets.CSE_NPM_TOKEN}}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}

      - name: Set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - name: Install depenency
        run: pnpm install

      - name: Clean build
        run: pnpm run clean:build

      - name: Build package
        run: pnpm run build:package

      - name: Build storybook
        run: pnpm run build:storybook
