name: PR Test

on:
  pull_request:
    branches: ['release']

env:
  NODE_VERSION: '18.13'
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  CSE_NPM_TOKEN: ${{secrets.CSE_NPM_TOKEN}}

jobs:
  test_code_convention:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}

      - name: Set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.5
          run_install: true

      - name: Check eslint
        run: pnpm lint

      - name: Check prettier
        run: pnpm prettier

  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}

      - name: Set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.5
          run_install: true

      - name: Clean build
        run: pnpm run clean:build

      - name: Build package
        run: pnpm run build:package

      - name: Build storybook
        run: pnpm run build:storybook
