name: Deploy canary package

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'

env:
  NODE_VERSION: '18.13'
  NPM_REGISTRY_URL: 'https://npm.pkg.github.com/'

jobs:
  Deploy:
    if: "contains(github.event.head_commit.message, 'deploy canary')"

    runs-on: ubuntu-latest
    env:
      CSE_NPM_TOKEN: ${{secrets.CSE_NPM_TOKEN}}

    steps:
      - name: Set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}

      - name: Regist author
        run: git config --global user.email "engineering@codestates.com" && git config --global user.name "CodeStates Engineering"
      
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.1
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Clean build
        run: pnpm run clean:build

      - name: Set new canary version
        run: pnpm run version:canary

      - name: Build Package
        run: pnpm run build:package

      - name: Deploy package(canary)
        run: pnpm run deploy:package:canary
