name: CD

on:
  push:
    branches:
      - 'release'

env:
  NODE_VERSION: '18.13'
  NPM_REGISTRY_URL: 'https://npm.pkg.github.com/'

jobs:
  CD:
    if: "!contains(github.event.head_commit.message, 'ver: ')"
    runs-on: ubuntu-latest
    env:
      CSE_NPM_TOKEN: ${{secrets.CSE_NPM_TOKEN}}

    steps:
      - name: Set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}

      - name: Install depenency(zero-install)
        run: yarn install

      - name: Regist author
        run: git config --global user.email "engineering@codestates.com" && git config --global user.name "CodeStates Engineering"

      - name: Pull release branch
        run: git pull

      - name: Set new patch version
        if: "!contains(github.event.head_commit.message, 'version-up ')"
        run: "npm version patch -m 'ver: %s'"

      - name: Set new minor version
        if: "contains(github.event.head_commit.message, 'version-up minor')"
        run: "npm version minor -m 'ver: %s'"

      - name: Set new major version
        if: "contains(github.event.head_commit.message, 'version-up major')"
        run: "npm version major -m 'ver: %s'"

      - name: Push release branch
        run: git push

      - name: Build Package
        run: yarn run build:package

      - name: Deploy package
        run: yarn run deploy:package

      - name: Build storybook
        run: yarn run build:storybook

      - name: Deploy storybook
        run: yarn run deploy:storybook
