name: PR Test

on:
  pull_request:
    branches: ['release']

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      CSE_NPM_TOKEN: ${{secrets.CSE_NPM_TOKEN}}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}

      - name: Set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Check eslint
        run: pnpm lint

      - name: Check prettier
        run: pnpm prettier

      - name: Check stylelint
        run: pnpm lint:style

      - name: Install dependencies
        run: pnpm install

      - name: Clean build
        run: pnpm run clean:build

      - name: Build package
        run: pnpm run build:package

      - name: Build storybook
        run: pnpm run build:storybook
